In [1]:
import numpy as np

In [2]:
listarray = np.array([[1,2,3,4], [5,6,7,8]])
print(listarray)
print(listarray.dtype)
print(listarray.shape)
print(listarray.size) #creates the list of arrays

[[1 2 3 4]
 [5 6 7 8]]
int32
(2, 4)
8


In [3]:
listarray.shape

(2, 4)

In [4]:
listarray.size

8

In [5]:
np.array({30,40,50}) #creates a dictionary

array({40, 50, 30}, dtype=object)

In [6]:
zeros=np.zeros((2,5))
print(zeros)
print(zeros.dtype)
print(zeros.size)
print(zeros.shape) #prints the matrix with zeros in it

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
float64
10
(2, 5)


In [7]:
rng=np.arange(15)
rng #it gives the number between the range

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [8]:
lspace=np.linspace(1,5,12)
lspace #it divides the number into equal parts

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [9]:
emp=np.empty((4,6))
emp #prints an empty array

array([[ 0.0000000e+000,  0.0000000e+000,  0.0000000e+000,
         0.0000000e+000,  0.0000000e+000,  0.0000000e+000],
       [ 0.0000000e+000,  0.0000000e+000,  0.0000000e+000,
         0.0000000e+000,  0.0000000e+000,  0.0000000e+000],
       [ 0.0000000e+000, -1.9236682e-310,  0.0000000e+000,
         0.0000000e+000,  0.0000000e+000,  0.0000000e+000],
       [ 0.0000000e+000,  0.0000000e+000,  0.0000000e+000,
         0.0000000e+000,  0.0000000e+000,  0.0000000e+000]])

In [10]:
ide=np.identity(45)
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [11]:
arr=np.arange(99)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98]


In [12]:
arr.reshape(3,33) #reshape the array

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [13]:
emp_like=np.empty_like(lspace)
emp_like #creates empty array of same size of given array

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [17]:
arr = np.array([[1,2,3,4], [5,6,7,8]])

In [18]:
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [20]:
arr1 = np.array([1,2,3,4])

In [21]:
arr1

array([1, 2, 3, 4])

In [23]:
np.max(arr1)

4

In [26]:
np.sum(arr)

36

In [27]:
np.add(arr,arr1)

array([[ 2,  4,  6,  8],
       [ 6,  8, 10, 12]])

In [28]:
np.sin(arr)

array([[ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ],
       [-0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825]])

In [35]:
np.power(arr,arr1)

array([[   1,    4,   27,  256],
       [   5,   36,  343, 4096]])

In [36]:
np.unique(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [39]:
np.intersection(arr,arr1)

AttributeError: module 'numpy' has no attribute 'intersection'